---
description: >-
  PyTest ve AsyncIO kullanan uygulamanÄ±zda 'Event loop is closed' sorunu mu
  yaÅŸÄ±yorsunuz? Bu rehberde, session kapsamÄ±nda ortak bir event_loop kullanarak
  bu hatayÄ± nasÄ±l Ã§Ã¶zeceÄŸinizi Ã¶ÄŸrenin.
---

# ğŸ”„ pytest ile asyncio RuntimeError: Event loop is closed sorunu Ã§Ã¶zÃ¼mÃ¼

* TÃ¼m `session` iÃ§erisinde ortak `event_loop` kullanmamÄ±z gerekir
* `pytestmark` iÅŸleminden Ã¶nce gelmesine dikkat edin

```python
from pytest import mark, fixture
from asyncio import get_event_loop_policy
from typing import Any

@fixture(scope="session")
def event_loop(request: Any):
    loop = get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()

pytestmark = mark.asyncio(timeout=5, scope="session")
```
